### ISSUE TITLE
hg19 REG2MAP_bed

### ISSUE THREAD

**Issue by yingjin07** [ENCODE-DCC/atac-seq-pipeline#36]
I got an error at the step of call-ataqc. I feel that the problem is caused by missing reg2map_bed file. I would like to know where can I download hg19 reg2map_bed file. Thanks!

**Comment by leepc12** [comment]
We already figured this out. This error will be fixed soon by end of this week.

**Comment by leepc12** [comment]
Fixed. please update (`git pull`) the pipeline and try again.

If you are using a Conda environment. Update pipeline source files in the Conda env by running the following command.
```
$ bash conda/update_conda_env.sh
```

**Comment by hoholee** [comment]
Sorry to re-open this issue, but I got a similar error when using hg19 genome downloaded using the `download_geome_data.sh` script. And the `REG2MAP_BED` filed is still missing in the script:

https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/46f2a928db20ca4889160b6e2a2e980fac34d672/scripts/download_genome_data.sh#L29-L46

**Comment by leepc12** [comment]
Fixed in commit a3512e4e0c929bd90c8aa7a0834dd19e1e315005.
This will be fixed in the next release.
