### ISSUE TITLE
Incompatibility issues with custom reference genome

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#47]
**Incompatibility issues with custom reference genome**  

Macs2 peak calling fails if the FASTA file used to build a custom genome database does not follow the `chr[\dXY]` naming convention. For example, I am using the Ensembl masked version of the rat genome (rn6, release 94) found here ftp://ftp.ensembl.org/pub/release-94/fasta/rattus_norvegicus/dna/, which does not prepend 'chr' to chromosome names. The error is produced by the following call:  
```bash
[2018-10-31 18:06:20,887 ERROR] Unknown exception caught. Killing process group 72093...
Traceback (most recent call last):
  File "/users/nicolerg/anaconda2/envs/encode-atac-seq-pipeline/bin/encode_common.py", line 224, in run_shell_cmd
    p.returncode, cmd)
CalledProcessError: Command 'cat /mnt/lab_data/montgomery/nicolerg/motrpac/atac/pipeline-output/cromwell-executions/atac/03a28d2a-f364-4ce1-bfd5-f10488cf42a9/call-macs2/shard-0/inputs/-78707573/rn6_masked.chrom.sizes | grep -P 'chr[\dXY]+[ \t]' > 20180725_2_Gastroc_002_powder_S1_L001_R1_001.trim.merged.nodup.tn5.pval0.01.300K.bfilt.chrsz.tmp' returned non-zero exit status 1
```

**OS/Platform and dependencies**
- Platform: Ubuntu 16.04.4
- Cromwell: cromwell-34
- Conda version: conda 4.5.11

**Comment by nicolerg** [comment]
[debug_incompatibilty_issues_w_custom_genome.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2539414/debug_incompatibilty_issues_w_custom_genome.tar.gz)

**Comment by nicolerg** [comment]
[debug_issue47.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2539418/debug_issue47.tar.gz)

**Comment by dianeking0** [comment]
I have similar issue using Schizosaccharomyces Pombe (yeast) where the chromosome names are roman numerals (I, II, III).  Fasta is found ftp://ftp.ensemblgenomes.org/pub/fungi/release-41/fasta/schizosaccharomyces_pombe/dna/

In investigating the problem, I found 

in file encode_common_genomic.py,  in function peaktobigbed, there is a line 
cmd1 = "cat {} | grep -P 'chr[\dXY]+[ \\t]' > {}".format(chrsz, chrsz_tmp)

if that was changed to 
cmd1 = "cat {} | grep -P '^(chr)*([\d]+|[XY]|[IVX]+)[ \\t]' > {}".format(chrsz, chrsz_tmp)

then both the rat and yeast genomes would pass. 

There is a similar line in file encode_blacklist_filter.py, function blacklist_filter
(cmd += 'grep -P \'^(chr[\\dXY]+|[IVX]+)[ \\t]\' | '  )  which would need to be changed also.

**Comment by akundaje** [comment]
@leepc12 We should modify all code that operates on chromosome names to make sure that it doesn't assume a format for the names. Lets discuss next time we meet.

**Comment by leepc12** [comment]
Sure, working on it and will be fixed in the next release.

**Comment by dianeking0** [comment]
Why exactly are you modifying the chrom.sizes file/list in situtation? (in file encode_common_genomic.py, in function peaktobigbed)

The  chrsz_tmp file is used as input to programs bedClip and bedToBigBed.
Both bedClip and bedToBigBed fail if a chromosome is found in the bed file but is missing in the chrom.size file. But the opposite (not found in the bed file but present in the chrom.size file) works fine.

**Comment by leepc12** [comment]
Fixed in branch `PIP-418_v1.1.2`. This will be merged into master soon.

Add the following to your input JSON and try again. with this parameter, pipeline will keep all peaks with irregular chromosome name.
```
   "atac.keep_irregular_chr_in_bfilt_peak" : true,
```

There was a code refactoring in v1.1.2. Some task level variables have moved to a workflow level. So please take a quick look at this `template_se.json` file (with all default parameters included) to check any namespace change in other parameters.
https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/PIP-418_v1.1.2/examples/template_se.json

**Comment by dianeking0** [comment]
The keep_irregular_chr_in_bfilt_peak fix worked for me. Thank you. 

I did notice some other issues with irregular chromosome names still present in the code.  
There are several places where the mitochondrial chromosome is hardcoded as chrM. 
Specifically in,
file                                             function
run_ataqc.py                              get_chr_m
                                                  get_mito_dups
encode_common_genomic.py  subsample_ta_se
                                                  subsample_ta_pe
encode_filter.py                         pbc_qc_se
                                                   pbc_qc_pe
                                                   make_mito_dup_log
encode_xcor.py                          xcor

bam2ta does not hardcode chrM but uses an optional argument (--regex-grep-v-ta) 
though that parameter is not listed in the INPUT json templates.
The parameter regex-filter-reads is listed but I can't find where it is used in the code.

**Comment by leepc12** [comment]
Sure, I am working on parameterizing ``atac.mito_chr_name` : "any_mito_chr_name"` in an input JSON. This will be fixed in the next release.

BTW `regex-filter-reads` is sort of a wrapper variable for `--regex-grep-v-ta` in `bam2ta`.
