### ISSUE TITLE
Error running test data with CONDA through virtualbox

### ISSUE THREAD

**Issue by sjquon** [ENCODE-DCC/atac-seq-pipeline#61]
**OS/Platform and dependencies**
- OS or Platform: macOS High Sierra running running Linux Virtual box 4.15.0-23-generic Ubuntu 64-bit
- Conda version: 4.5.11

I get an error while running the test data on the pipeline that says that it failed to find index Success(WomInteger(0)) on array. The error is shown below 

```
WorkflowManagerActor Workflow 7a43f040-d436-4dbc-9596-8fbbccfa2827 failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'filter.flagstat_qc': Failed to find index Success(WomInteger(0)) on array:

Success([])

0
Bad output 'filter.dup_qc': Failed to find index Success(WomInteger(0)) on array:

Success([])

0
Bad output 'filter.pbc_qc': Failed to find index Success(WomInteger(0)) on array:

Success([])

0
Bad output 'filter.mito_dup_log': Failed to find index Success(WomInteger(0)) on array:

Success([])

0
	at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$handleExecutionSuccess$1(StandardAsyncExecutionActor.scala:839)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

I have attached the tar ball. 
I have also captured my session using script which is attached as the typescript.

I followed the instructions posted on the github for Tutorial for general UNIX computers without docker. I'm not sure what this error message means and was hoping that you had some advice to fix this. Thanks!

 
[typescript.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2635307/typescript.txt)
[debug_61.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2635318/debug_61.tar.gz)

**Comment by leepc12** [comment]
This will be fixed in the next release (v1.1.3). Until then, please try with singularity or docker instead.

**Comment by sjquon** [comment]
I see. Thank you.

**Comment by leepc12** [comment]
It's a different error.
```
Error occurred during initialization of VM
Could not reserve enough space for 4194304KB object heap
```
How much memory do you have on your virtual machine?

**Comment by dcdxy** [comment]
Ok. Should I create a new issue?

**Comment by leepc12** [comment]
@dcdxy : Please look at the error message above. Give enough memory to your VM.

**Comment by dcdxy** [comment]
Sorry, I thought you were referring to sjquon (VM) as I'm using a compute cluster. Do you mean that I should set resources per task in the input JSON (i.e. `"atac.filter_mem_mb"`)? Or is there a global parameter that I should set in `sge.json`?

**Comment by leepc12** [comment]
Resource settings are not in `sge.json`. Yes, it's `"atac.filter_mem_mb"` in your input JSON file. But it's 16GB by default. I think your cluster has some limit on max. memory of Java VM?

**Comment by dcdxy** [comment]
I increased `"atac.filter_mem_mb"` from 4000 to 20000 which eliminated the VM initialization error. I received another memory error for a different step, so I increased all memory settings in the test sample's input JSON file as a precaution: 
                                                                                                                                                                               
```
    "atac.bowtie2_mem_mb" : 20000,
    "atac.filter_mem_mb" : 20000,
    "atac.macs2_mem_mb" : 20000,
    "atac.ataqc.mem_mb" : 20000,
``` 
 
I now receive a new error in the final step:

```
Picked up _JAVA_OPTIONS: -Xms256M -Xmx16000M -XX:ParallelGCThreads=1
Picked up _JAVA_OPTIONS: -Xms256M -Xmx16000M -XX:ParallelGCThreads=1 

IOError: [Errno 2] No such file or directory:
'ENCFF641SFZ.subsampled.400.trim.merged.picardcomplexity.qc' 
ln: failed to access ‘*_qc.html’: No such file or directory
ln: failed to access ‘*_qc.txt’: No such file or directory
``` 
which seems to arise from earlier errors in the reproducibility steps:

`ln: failed to access ‘conservative_peak.*.hammock_gz*’: No such file or directory`

Please find log files here: 
[debug_61_3.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2727574/debug_61_3.tar.gz)

**Comment by leepc12** [comment]
That `hammock_gz` error has already been fixed in v1.1.4 (on current master branch). Which version are you using? Can you update the pipeline and try again?

BTW is there any reason for you to use VM instead of simply running pipelines on a OSX terminal?

**Comment by dcdxy** [comment]
I updated the pipeline to v1.1.4 which eliminates the `hammock_gz` error, but I still get the first error:

`IOError: [Errno 2] No such file or directory: 'ENCFF341MYG.subsampled.400.trim.merged.picardcomplexity.qc'`

From `stdout` in the same directory (`call-ataqc`), it appears that it's another VM initialization error:

```
Error occurred during initialization of VM
Could not reserve enough space for 16384000KB object heap
```
but I have `"atac.ataqc.mem_mb" : 16000` which is the default in the example input JSON. I just noticed that there is a different parameter `"atac.ataqc_mem_java_mb"` that I haven't set... the default in the example JSON is also 16000 but it looks like the VM would require more space? Should I increase both of these parameters?

Please find log files here:
[debug_61_4.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2733360/debug_61_4.tar.gz)

Also I'm running the pipelines on our SGE cluster because this is where the data is stored and where I do the rest of my analyses, but I could potentially switch to using my local machine if necessary.

**Comment by leepc12** [comment]
Please reduce both `atac.ataqc_mem_mb` and `atac.ataqc_mem_java_mb` to `6000` and `5000` and then try again.

**Comment by dcdxy** [comment]
I made those changes and now receive the following: 

```
# 
# A fatal error has been detected by the Java Runtime Environment: 
#
#  Internal Error (g1PageBasedVirtualSpace.cpp:43), pid=15064, tid=15065
#  guarantee(rs.is_reserved()) failed: Given reserved space must have been reserved already.
#  
# JRE version:  (11.0.1+13) (build ) 
# Java VM: OpenJDK 64-Bit Server VM (11.0.1+13-LTS, mixed mode, aot, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Core dump will be written. Default location: Core dumps may be processed with "/usr/libexec/abrt-hook-ccpp %s %c %p %u %g %t e"
```

Please see attached: [debug_61_5.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2734409/debug_61_5.tar.gz)

**Comment by leepc12** [comment]
1) I think it's almost done. Pipeline failed at the final HTML reporting step because you didn't update the conda environment after updating the pipeline. Please run this on your pipeline git directory.
```
$ bash conda/update_conda_env.sh
```

2) The latest cromwell (36) has some known bugs/issues. Please use cromwell-34 until it's fixed in 37.

3) You can simply ignore that "dead letters encountered" warning.

4) BTW installing OracleJRE does not require super-user privileges.

**Comment by dcdxy** [comment]
Thank you--I ran the above command and successfully ran the test samples through the pipeline (keeping `"atac.disable_ataqc" : true`).
